name: eShopOnWeb Build and Test

# Triggers
on: [push, workflow_dispatch]

# Environment variables
env:
  RESOURCE_GROUP: rg-eshoponweb
  LOCATION: westus2
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: c8f0f5fd-35e6-4eec-a6b5-6bbb2ece0fa8
  WEBAPP_NAME: eshoponweb-webapp50232344

jobs:
  # Build, test and publish .NET web project
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore, Build, Test, and Publish
      - name: Restore with dotnet
        run: dotnet restore ./eShopOnWeb.sln

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: Publish with dotnet
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
          cd ${{ env.DOTNET_ROOT }}/myapp
          zip -r ../app.zip .

      # Upload app artifact
      - name: Upload .NET app artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.DOTNET_ROOT }}/app.zip

      # Upload Bicep template artifact
      - name: Upload Bicep template artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  # Deploy infrastructure and webapp
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      # Download .NET app artifact
      - name: Download .NET app artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: dotnet-app

      # Download Bicep template artifact
      - name: Download Bicep template artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy infrastructure using Bicep
      - name: Deploy infrastructure with Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: bicep-template/webapp.bicep
          parameters: 'webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false

      # Deploy app using Azure CLI
      - name: Publish website to Azure WebApp via CLI
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path dotnet-app/app.zip \
              --type zip
